[2024-12-18T22:33:28.610+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline.env_preparation manual__2024-12-18T22:33:26.337120+00:00 [queued]>
[2024-12-18T22:33:28.618+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline.env_preparation manual__2024-12-18T22:33:26.337120+00:00 [queued]>
[2024-12-18T22:33:28.618+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-12-18T22:33:28.635+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): env_preparation> on 2024-12-18 22:33:26.337120+00:00
[2024-12-18T22:33:28.643+0000] {standard_task_runner.py:60} INFO - Started process 1708 to run task
[2024-12-18T22:33:28.646+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline', 'env_preparation', 'manual__2024-12-18T22:33:26.337120+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmp6xclis61']
[2024-12-18T22:33:28.649+0000] {standard_task_runner.py:88} INFO - Job 129: Subtask env_preparation
[2024-12-18T22:33:28.699+0000] {task_command.py:423} INFO - Running <TaskInstance: data_pipeline.env_preparation manual__2024-12-18T22:33:26.337120+00:00 [running]> on host 1d3bd1c7da18
[2024-12-18T22:33:28.773+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline' AIRFLOW_CTX_TASK_ID='env_preparation' AIRFLOW_CTX_EXECUTION_DATE='2024-12-18T22:33:26.337120+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-18T22:33:26.337120+00:00'
[2024-12-18T22:33:28.790+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-18T22:33:28.800+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_pipeline, task_id=env_preparation, execution_date=20241218T223326, start_date=20241218T223328, end_date=20241218T223328
[2024-12-18T22:33:28.859+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-18T22:33:28.885+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
